package main

import (
  "world/concurrency"
  "world/methods"
  "hello/testlog"
)

func main() {
  // flowcontrol.F0()
  // flowcontrol.F1()
  // fmt.Println(flowcontrol.Sqrt(2), flowcontrol.Sqrt(-4))
  // fmt.Println(flowcontrol.Pow(3, 2, 10), flowcontrol.Pow(3, 3, 20))
  // flowcontrol.F8_customize_sqrt(169)
  // flowcontrol.My_customize_extraction(27)
  // flowcontrol.F9_switch()
  // flowcontrol.F10_switch_evaluation_order()
  // flowcontrol.F11_switch_with_no_condition()
  // flowcontrol.F12_defer()
  // moretypes.F6_array()
  // moretypes.F8_slice()
  // moretypes.F11_slice_len_cap()
  // moretypes.F13_make_slice()
  // moretypes.F14_complex_slice()
  // moretypes.F15_slice_append()
  // moretypes.F16_range()
  // moretypes.F19_map()
  // moretypes.F22_mutating_maps()
  // moretypes.F23_map_exercise()
  // moretypes.F24_wrapper()
  // methods.F1_methods()
  methods.F9_interfaces()
  // methods.F15_type_assertions()
  // methods.F21_readers()
  // methods.F23_rot13Reader()
  // methods.F24_Images()
  // concurrency.F1_Goroutines()
  // concurrency.F2_Channels()
  // concurrency.F3_buffered_chan()
  // concurrency.F4_range_close()
  // concurrency.F5_select()
  // concurrency.F6_default_selection()
  // concurrency.F8_equivalent_bitree()
  // concurrency.F9_sync_mutex()
  // concurrency.F10_web_crawler()
  // hehello.test_struct_method()
  // fmt.Println("hello world!")
  // read(write())
  // test_slice_array()
  // test_map()
  // test_struct_method()

  testlog.F()
  // testlog.F()
}
